# Generated by Django 4.1.6 on 2023-03-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
